// AUTO-GENERATED build-time seed for the webinar/summit replay pages (from the sheet).
// Live sheet data refreshes these in the browser; regenerate if the schema changes.
export const webinarReplaysSeed = [
  {
    slug: `the-resurgence-of-independent-veterinary-practice-balancing-autonomy`,
    date: `September 17, 2025`,
    duration: `0:56:29`,
    category: `Monthly Webinar Series`,
    title: `The Resurgence of Independent Veterinary Practice: Balancing Autonomy with Efficient Business Models`,
    subtitle: ``,
    image: `https://drive.google.com/thumbnail?id=1Ow7UIfICuWEC3_2f57eZLpNZicEMcV_B&sz=w1200`,
    href: `https://player.vimeo.com/video/1202092411`,
    summary: `This webinar dives into why independence is resurging, the opportunities it offers, and how to thrive without sacrificing efficiency or patient care.`,
    description: `https://docs.google.com/document/d/15prsxKsqpe_kncO5whDpd98_pU7_12eMPDt3eZ3yto0/edit?usp=sharing`,
    transcript: `https://docs.google.com/document/d/1A_9Y9rWl99iQYVxcA2jrNdNuFb_6C-1KOA4vvVpgkBc/edit?usp=sharing`,
  },
  {
    slug: `the-culture-multiplier-how-people-and-profits-together-define-true`,
    date: `October 15, 2025`,
    duration: `0:55:54`,
    category: `Monthly Webinar Series`,
    title: `The Culture Multiplier: How People and Profits Together Define True Veterinary Practice Value`,
    subtitle: ``,
    image: `https://drive.google.com/thumbnail?id=1z7uQr4QGUfX80kUcr_jlcuMbhySQJoI-&sz=w1200`,
    href: `https://player.vimeo.com/video/1127734650`,
    summary: `This webinar explores how culture serves as the ultimate multiplier for growth, retention, and client loyalty, while marketing translates that culture into measurable business value.`,
    description: `https://docs.google.com/document/d/1fhPTu-PxcmzHwH6N6fa8f5qQaiHinbE6IEmrZBUbbho/edit?usp=sharing`,
    transcript: `https://docs.google.com/document/d/1PJ6yoxRfglSNpHVKaXlr_fCAvCpduc9DTZ4SGwDyQ1I/edit?usp=sharing`,
  },
  {
    slug: `strengthening-modern-veterinary-clinics-through-culture-communication`,
    date: `January 29, 2026`,
    duration: `1:07:18`,
    category: `Monthly Webinar Series`,
    title: `Strengthening Modern Veterinary Clinics Through Culture, Communication, Technology, Client Care, and Marketing`,
    subtitle: ``,
    image: `https://drive.google.com/thumbnail?id=1uS0L6Rt3MeqWbNdtC778z2lMldRXCOdB&sz=w1200`,
    href: `https://player.vimeo.com/video/1160032913`,
    summary: `This webinar takes a focused look at five essential pillars every modern clinic must strengthen to stay competitive: culture, communication, technology, client care, and marketing.`,
    description: `https://docs.google.com/document/d/18p5A2B1CHCglg0exohcE9FyQDXqQtVjSol3q4ZD-6bQ/edit?usp=sharing`,
    transcript: `https://docs.google.com/document/d/1Cr_WNsqwRa-gYoom3UsyD8B7OKNszaWuC0tq5yI7e4Y/edit?usp=sharing`,
  },
  {
    slug: `elevating-veterinary-practice-performance-through-marketing-technology`,
    date: `March 26, 2026`,
    duration: `1:38:55`,
    category: `Monthly Webinar Series`,
    title: `Elevating Veterinary Practice Performance Through Marketing, Technology, Team Productivity, and Financial Resilience`,
    subtitle: ``,
    image: `https://drive.google.com/thumbnail?id=1ovH2jlh7Rb8SOVDD5NrvIa-zFY4x4s2q&sz=w1200`,
    href: `https://player.vimeo.com/video/1177554950`,
    summary: `This webinar explores practical strategies to increase clinic visibility, attract high-quality clients, and strengthen your brand through focused, efficient marketing.`,
    description: `https://docs.google.com/document/d/1HnJyi6JCTaTz11uIPszoccWfUspJ3qO0G5PzjkDBQho/edit?usp=sharing`,
    transcript: `https://docs.google.com/document/d/16b_eShIET5bT4Vqtr-iefkazTLExXdpay4OoyVvZkwE/edit?usp=sharing`,
  },
  {
    slug: `driving-veterinary-practice-profitability-and-client-loyalty-through`,
    date: `April 23, 2026`,
    duration: `1:04:58`,
    category: `Monthly Webinar Series`,
    title: `Driving Veterinary Practice Profitability and Client Loyalty Through Financial Strategy, Communication, and Marketing`,
    subtitle: ``,
    image: `https://drive.google.com/thumbnail?id=1OJoKQ98SVzvZDNH1VU2uj4noRWkkkkt3&sz=w1200`,
    href: `https://player.vimeo.com/video/1186126719`,
    summary: `This webinar reveals how stronger accounting, communication, and marketing practices can improve profitability, team alignment, and client retention.`,
    description: `https://docs.google.com/document/d/1snmr29j33o7Hozd6w_wIdSJR1kw90Cpm_9x71hS7KOA/edit?usp=sharing`,
    transcript: `https://docs.google.com/document/d/13KlPnh5Hfqj8VdqrufbwGiAEqQghAjccU2utZYHfFCA/edit?usp=sharing`,
  },
  {
    slug: `driving-veterinary-practice-growth-leveraging-technology-marketing`,
    date: `June 30, 2026`,
    duration: `1:31:24`,
    category: `Monthly Webinar Series`,
    title: `Driving Veterinary Practice Growth: Leveraging Technology, Marketing, Operations, and Client Experience to Increase Revenue and Loyalty`,
    subtitle: ``,
    image: `https://drive.google.com/thumbnail?id=1RTvn5gUkTOy9DJslZ5mg3_ElyiX7xOE-&sz=w1200`,
    href: `https://player.vimeo.com/video/1207456943`,
    summary: `This webinar is structured around four critical pillars that drive modern veterinary practice success: technology, marketing, operations, and client experience.`,
    description: `https://docs.google.com/document/d/1CbTAb8Pb4AjENinA2EXOGNZ7VkzIF8eEiF_wMlceFYI/edit?usp=sharing`,
    transcript: `https://docs.google.com/document/d/1x8-pYDhQDj_0xxUGB0rXBjp9v0CgzuDhzdYYIqM3seU/edit?usp=sharing`,
  },
  {
    slug: `profitability-gets-tight-fast-when-veterinary-pricing-outruns-pet-owner`,
    date: `July 23, 2026`,
    duration: `1:03:19`,
    category: `Monthly Webinar Series`,
    title: `Profitability Gets Tight Fast When Veterinary Pricing Outruns Pet Owner Perceived Value: Reworking Financial Strategy, Client Communication, and Marketing`,
    subtitle: ``,
    image: `https://drive.google.com/thumbnail?id=1i1X7eoLsXerGBz-ObYjVdnL8utMTha17&sz=w1200`,
    href: `https://player.vimeo.com/video/1212548526`,
    summary: `In this webinar, industry leaders explored how veterinary practices can strengthen profitability without relying solely on fee increases.`,
    description: `https://docs.google.com/document/d/1XicchaKGku4NES4bIwlOTsSecNxNdcGAS6YWkAt98hM/edit?usp=sharing`,
    transcript: `https://docs.google.com/document/d/1umCvGgJomUxIkkhdtJsUBppAloUsNsIjhYk8W8VLMzs/edit?usp=sharing`,
  },
];

export const summitReplaysSeed = [
  {
    slug: `vet-evolution-shaping-the-future-with-innovation-empathy-and-growth`,
    date: `July 30, 2025`,
    duration: `2:02:41`,
    category: `Monthly Summit`,
    title: `Vet Evolution: Shaping the Future with Innovation, Empathy, and Growth.`,
    subtitle: ``,
    image: `https://drive.google.com/thumbnail?id=1VqTkybnHUIX3au6kkOm2gw8DhKt6pcX6&sz=w1200`,
    href: `https://player.vimeo.com/video/1202031594`,
    summary: `This multi-disciplinary summit brings together visionaries from across the veterinary ecosystem to share bold, practical insights that shape the future of veterinary care.`,
    description: `https://docs.google.com/document/d/1gzg0HDFDLy7Zd_3VFvNVwBc1qYe4oSkokU-BEOX3mUw/edit?usp=sharing`,
    transcript: `https://docs.google.com/document/d/19G38pxvR13uD3k4JOHbCBQk2anxZUYd03Yk0effD5To/edit?usp=sharing`,
  },
  {
    slug: `uniting-technology-talent-and-compassion-to-shape-the-next-generation`,
    date: `August 29, 2025`,
    duration: `1:52:17`,
    category: `Monthly Summit`,
    title: `Uniting Technology Talent and Compassion to Shape the Next Generation of Veterinary Practice`,
    subtitle: ``,
    image: `https://drive.google.com/thumbnail?id=1YG0ROhaa7PqQMjyEcpbgeseKCGkX9L71&sz=w1200`,
    href: `https://player.vimeo.com/video/1120027237`,
    summary: `This transformative summit brings together experts from across veterinary medicine, technology, HR, finance, and leadership to explore how innovation, talent development, and empathy are converging to define the next era of practice success.`,
    description: `https://docs.google.com/document/d/1idQCskyxz8TLqgafm4qNSz3nw1DAO1QyL6C5jjR4nhk/edit?usp=sharing`,
    transcript: `https://docs.google.com/document/d/19dSEHycZ9jzd4q6F4zWmwGzViQKlFYRxvTopuRdb11Q/edit?usp=sharing`,
  },
  {
    slug: `what-the-future-demands-of-veterinary-practices-across-compliance`,
    date: `September 24, 2025`,
    duration: `1:59:59`,
    category: `Monthly Summit`,
    title: `What the Future Demands of Veterinary Practices Across Compliance, Culture, Growth and Innovation`,
    subtitle: ``,
    image: `https://drive.google.com/thumbnail?id=1BaSO34x9KicHBvw4FMoZg0KOh5tDQa-l&sz=w1200`,
    href: `https://player.vimeo.com/video/1122714883`,
    summary: `In this powerful webinar, experts in compliance, culture, profitability, innovation, and growth will share the strategies future-ready practices are already using. You’ll walk away with practical insights to protect your clinic, strengthen your team, engage your clients, and build long-term resilience.`,
    description: `https://docs.google.com/document/d/1b4Ofd0MpWNXnMBY7H2ZhhlaFpWgjhlgjQ_zRNH52NI8/edit?usp=sharing`,
    transcript: `https://docs.google.com/document/d/1iJ0VO9FMlyJ0lSPv2yEhbEdk0VeuDaVRpxhX1b8SU5I/edit?usp=sharing`,
  },
  {
    slug: `six-forces-shaping-the-next-decade-of-veterinary-business-law-marketing`,
    date: `October 23, 2025`,
    duration: `2:01:38`,
    category: `Monthly Summit`,
    title: `Six Forces Shaping the Next Decade of Veterinary Business: Law, Marketing, Leadership, Culture, Finance, and AI`,
    subtitle: ``,
    image: `https://drive.google.com/thumbnail?id=1riobVl_UcMSMVQKet_MS5Fa95XZW9imb&sz=w1200`,
    href: `https://player.vimeo.com/video/1130150186`,
    summary: `This webinar unpacks the six forces that will determine the future of the veterinary business. You’ll gain insights from across disciplines, discover strategies for long-term growth, and learn how to position your practice to thrive in an environment where change is the only constant.`,
    description: `https://docs.google.com/document/d/1PRtz38uhC1doiEoz3S6a25LIALg4A7HskkQIcENHbCs/edit?usp=sharing`,
    transcript: `https://docs.google.com/document/d/1HdqkN1-XcOY9QFWHGPJ6PzyId5-A02ixFdJhEoQKoMs/edit?usp=sharing`,
  },
  {
    slug: `the-biggest-challenges-facing-veterinary-practice-owners-today-are-you`,
    date: `December 10, 2025`,
    duration: `2:08:36`,
    category: `Monthly Summit`,
    title: `The Biggest Challenges Facing Veterinary Practice Owners Today — Are You Keeping Up or Falling Behind?`,
    subtitle: ``,
    image: `https://drive.google.com/thumbnail?id=1MSwxQIL3FCP5X-qiPL4pUjHo1ZC3hA2y&sz=w1200`,
    href: `https://player.vimeo.com/video/1145492385`,
    summary: `This summit brings together top experts in Marketing, Finance, Law, Leadership, and Practice Management to uncover the biggest challenges facing veterinary practices today — and more importantly, how to overcome them.`,
    description: `https://docs.google.com/document/d/1b0bOANZAuGxl0ulDKXYCEnN33kz_eiscAXe7viU2Hvo/edit?usp=sharing`,
    transcript: `https://docs.google.com/document/d/1cfum7hk8YGbnJ98UR55YrNTib8J65IB5tqyL9l9ZLtE/edit?usp=sharing`,
  },
  {
    slug: `shaping-future-ready-veterinary-practices-through-strategic-planning`,
    date: `February 19, 2026`,
    duration: `1:01:17`,
    category: `Monthly Summit`,
    title: `Shaping Future-Ready Veterinary Practices Through Strategic Planning, Culture, Retention, Financial Resilience, Marketing and Practice Continuity`,
    subtitle: ``,
    image: `https://drive.google.com/thumbnail?id=1blyfeBQ-v5cuD6UnlqbRWDOuko-xwGfx&sz=w1200`,
    href: `https://player.vimeo.com/video/1166544212`,
    summary: `This webinar equips practice leaders to drive sustainable growth, strengthen financial and operational resilience, and deliver consistently exceptional client experiences.
Discover practical strategies to engage and retain teams, build accountability, manage change, and protect long-term practice continuity.`,
    description: `https://docs.google.com/document/d/1WXz6Ome0YvCAdEKnP_VF_PVNoZxSKirmWwVbbZD7_tM/edit?usp=sharing`,
    transcript: `https://docs.google.com/document/d/1pvFz4-couNJd9mgAbw7uqqa7YCbTTu94MklX1tIxZ2E/edit?usp=sharing`,
  },
  {
    slug: `why-hard-working-veterinary-practices-still-struggle-fixing-finances`,
    date: `May 21, 2026`,
    duration: `2:07:07`,
    category: `Monthly Summit`,
    title: `Why Hard-Working Veterinary Practices Still Struggle: Fixing Finances, Retention, Marketing, and Leadership Gaps`,
    subtitle: ``,
    image: `https://drive.google.com/thumbnail?id=1T7zTvdRtKXbvPU5wNZ3R-cyHAtaR4kB0&sz=w1200`,
    href: `https://player.vimeo.com/video/1194598423`,
    summary: `This webinar helps practice leaders uncover financial blind spots, improve team retention, align marketing with operational capacity, and make more confident leadership decisions.`,
    description: `https://docs.google.com/document/d/1_Xrm9tAP55dlh6W32yRhbLhKrDw9W4jafRf_Z9EmlVI/edit?usp=sharing`,
    transcript: `https://docs.google.com/document/d/1cnsXaGKOe1krruGaC6ogs-uSUYXGbSVToHTC2yUermE/edit?usp=sharing`,
  },
];
